"""Config"""

### Variables
#DATABASE = './database.db'
PER_PAGE = 30
DEBUG = True
SECRET_KEY = 'junctionmgls' # secret key for app

# mysql settings
MYSQL_DATABASE_HOST = <HOST>
MYSQL_DATABASE_PORT = <PORT>
MYSQL_DATABASE_USER = <USERNAME>
MYSQL_DATABASE_PASSWORD = <PASSWORD>
MYSQL_DATABASE_DB = <DATABASE>
MYSQL_DATABASE_CHARSET = 'utf8'
SQLALCHEMY_DATABASE_URI = <URI>